s3851781-a2-main/AdminWebsite/Controllers/AdminLoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using AdminWebsite.Models;

namespace AdminWebsite.Controllers;

[AllowAnonymous]
public class AdminLoginController : Controller
{
    private string loggedInState => HttpContext.Session.GetString("loggedInState");

    public IActionResult Index() => View();

    [HttpPost]
    public IActionResult Index(AdminLogin adminLogin)
    {
        var login = adminLogin.Username == "admin" && adminLogin.Password == "admin";

        if (!login)
        {
            ModelState.AddModelError("Login Failed", "Login failed, please try again.");
            return View(adminLogin);
        }

        // Login admin.
        HttpContext.Session.SetString("loggedInState", "loggedIn");
        return RedirectToAction("Index", "Home");
    }

    public IActionResult Logout()
    {
        // Logout customer.
        HttpContext.Session.Clear();

        return RedirectToAction("Index", "Home");
    }

}

s3851781-a2-main/AdminWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            var isLoggedIn = Context.Session.GetString("loggedInState") != null;
                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item m-2">
                                <a class="" asp-controller="AdminLogin" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item m-2">
                                <a class="btn btn-outline-primary" asp-controller="AdminLogin" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>