s3851781-a3-main/MvcStore/Models/ErrorViewModel.cs
namespace MvcStore.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

s3851781-a3-main/MvcStore/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebApi.Validators;

namespace MvcStore.Models;

public class Order
{
    [Key]
    [Required]
    [Display(Name = "Order ID")]
    public int OrderID { get; set; }

    [Required]
    [DateTime]
    [DataType(DataType.Date)]
    [Display(Name = "Order Date")]
    public DateTime OrderDate { get; set; }

    [Required]
    [CustomerNameAttribute]
    [StringLength(50)]
    public string CustomerName { get; set; }

    [Required]
    [StringLength(200)]
    public string DeliveryAddress { get; set; }

    [DateTime]
    [DataType(DataType.Date)]
    public DateTime? DeliveredDate { get; set; }

    public ICollection<OrderedProducts> OrderedProducts { get; set; }
}

s3851781-a3-main/MvcStore/Models/OrderDTO.cs
using System.ComponentModel.DataAnnotations;

namespace MvcStore.Models;

public class OrderDTO : Order
{
    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0")]
    public int Quantity { get; set; }
    
}

s3851781-a3-main/MvcStore/Models/OrderedProducts.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebApi.Validators;

namespace MvcStore.Models;

public class OrderedProducts
{
    [Key]
    [Required]
    [Display(Name = "Order ID")]
    public int OrderID { get; set; }
    public Order Order { get; set; }

    [Key]
    [Required]
    [Display(Name = "Product ID")]
    public int ProductID { get; set; }
    public Product Product { get; set; }

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0")]
    public int Quantity { get; set; }
}

s3851781-a3-main/MvcStore/Models/OrderedProductsViewModel.cs
namespace MvcStore.Models;

public class OrderedProductsViewModel
{
    public IEnumerable<OrderedProducts> OrderedProducts { get; set; }
    public IEnumerable<Product> Products { get; set; }
}

s3851781-a3-main/MvcStore/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using WebApi.Validators;

namespace MvcStore.Models;

public class Product
{
    [Key]
    [Required]
    [Display(Name = "Product ID")]
    public int ProductID { get; set; }

    [Required]
    [ProductNameAttribute]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [Column(TypeName = "decimal")]
    [DataType(DataType.Currency)]
    public decimal Price { get; set; }

}

s3851781-a3-main/MvcStore/Controllers/Api/OrdersApiController.cs
using Microsoft.AspNetCore.Mvc;
using MvcStore.Data;
using MvcStore.Models;


namespace MvcStore.Api.Controllers;

// See here for more information:
// https://docs.microsoft.com/en-au/aspnet/core/web-api/?view=aspnetcore-7.0

[ApiController]
[Route("api/orders")]
public class OrdersApiController : ControllerBase
{
    private readonly MvcStoreContext _context;

    public OrdersApiController(MvcStoreContext context)
    {
        _context = context;
    }
    
    // GET: api/orders
    [HttpGet]
    public IEnumerable<OrderDTO> Get()
    {
        var orders = _context.Order.Select(x => new OrderDTO
        {
            OrderID = x.OrderID,
            OrderDate = x.OrderDate,
            CustomerName = x.CustomerName,
            DeliveryAddress = x.DeliveryAddress,
            DeliveredDate = x.DeliveredDate,
            Quantity = x.OrderedProducts.Sum(y => y.Quantity)
        }).ToList();

        return orders;
    }
}

s3851781-a3-main/MvcStore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcStore.Models;

namespace MvcStore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return RedirectToAction("Index", "Products");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

s3851781-a3-main/MvcStore/Controllers/OrderedProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcStore.Models;
using MvcStore.Data;
using Microsoft.EntityFrameworkCore;

namespace MvcStore.Controllers;

public class OrderedProductsController : Controller
{
    private readonly MvcStoreContext _context;

    public OrderedProductsController(MvcStoreContext context)
    {
        _context = context;
    }

    // GET: OrderedProducts/Index
    public async Task<IActionResult> Index(string productName)
    {
        var orderedProducts = await _context.OrderedProducts.Select(x => x).Include(x => x.Order).Include(x => x.Product).ToListAsync();
        if (!String.IsNullOrEmpty(productName))
        {
            orderedProducts = orderedProducts.Where(x => x.Product.Name.Contains(productName)).ToList();
        }

        var products = await _context.Product.Select(x => x).ToListAsync();


        var viewModel = new OrderedProductsViewModel
        {
            OrderedProducts = orderedProducts,
            Products = products
        };
        
        return View(viewModel);
    }

}

s3851781-a3-main/MvcStore/Controllers/OrdersController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using MvcStore.Models;
using Newtonsoft.Json;

namespace MvcStore.Controllers;

public class OrdersController : Controller
{
    private readonly IHttpClientFactory _clientFactory;
    private HttpClient Client => _clientFactory.CreateClient();

    public OrdersController(IHttpClientFactory clientFactory) => _clientFactory = clientFactory;

    // GET: Orders/Index
    public async Task<IActionResult> Index()
    {
        var response = await Client.GetAsync("api/orders");

        if(!response.IsSuccessStatusCode)
            throw new Exception();

        // Storing the response details received from web api.
        var result = await response.Content.ReadAsStringAsync();

        // Deserializing the response received from web api and storing into a list.
        var orders = JsonConvert.DeserializeObject<List<OrderDTO>>(result);

        return View(orders);
    }
    
}

s3851781-a3-main/MvcStore/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcStore.Models;
using MvcStore.Data;
using Microsoft.EntityFrameworkCore;

namespace MvcStore.Controllers;

public class ProductsController : Controller
{
    private readonly MvcStoreContext _context;

    public ProductsController(MvcStoreContext context)
    {
        _context = context;
    }

    // GET: Products/Index
    public async Task<IActionResult> Index()
    {
        var products = await _context.Product.Select(x => x).ToListAsync();
        return View(products);
    }

    // GET: Products/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Products/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Product product)
    {
        if(ModelState.IsValid)
        {
            _context.Product.Add(product);
            _context.SaveChanges();
            return RedirectToAction("Index");                
        }

        return View(product);
    }
        
}

s3851781-a3-main/MvcStore/Views/OrderedProducts/Index.cshtml
@model OrderedProductsViewModel
@{
    ViewData["Title"] = "Ordered Products";
    var products = Model.Products;
}

<h1>Ordered Products</h1>
<div class="p-2"></div>
@using (Html.BeginForm("Index", "OrderedProducts", FormMethod.Get))
{
    <div class="form-group">
        <label for="productName">Filter by Product</label>
        @Html.DropDownList("productName", products.Distinct().Select(x => new SelectListItem { Text = x.Name, Value = x.Name }), "All Products",
    new { @class = "form-control", id = "productName" })
        
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
}
    
<div class="p-4"></div>

<partial name="_OrderedProductsTable" for="OrderedProducts" />

s3851781-a3-main/MvcStore/Views/Products/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Create Product";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

s3851781-a3-main/MvcStore/Views/Products/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "All Products";
}

<h1>All Products</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>
        }
    </tbody>
</table>