s3851781-a2-main/CustomerWebsite/Models/Account.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CustomerWebsite.Models.Types;
namespace CustomerWebsite.Models;

public partial class Account
{
    [Key]
    [Required]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [StringLength(4, MinimumLength = 4)]
    [Display(Name = "Account Number")]
    public int AccountNumber { get; set; }

    [Required]
    [StringLength(1, MinimumLength = 1)]
    [RegularExpression(@"^(C|S)$", ErrorMessage = "Account type must be either Checkings or Savings")]
    [Display(Name = "Account Type")]
    public string AccountType { get; set; }

    [ForeignKey(nameof(Customer))]
    [Required]
    public int CustomerID { get; set; }
    public Customer Customer { get; set; }

    [InverseProperty(nameof(Transaction.Account))]
    public ICollection<Transaction> AccountTransactions { get; } = new List<Transaction>();
    
    [InverseProperty(nameof(Transaction.DestinationAccount))]
    public ICollection<Transaction> DestinationAccountTransactions { get; } = new List<Transaction>();
    
    public decimal GetBalance()
    {
        decimal balance = 0;
        foreach (var transaction in AccountTransactions)
        {
            switch (transaction.TransactionType)
            {
                case TransactionType.Deposit:
                    balance += transaction.Amount;
                    break;
                case TransactionType.Withdraw:
                    balance -= transaction.Amount;
                    break;
                case TransactionType.BillPay:
                    balance -= transaction.Amount;
                    break;
                case TransactionType.Transfer:
                    if (transaction.DestinationAccountNumber == null)
                    {
                        balance += transaction.Amount;
                    }
                    else
                    {
                        balance -= transaction.Amount;
                    }
                    break;
            }
        }
        return balance;
    }
    public string GetBalanceString()
    {
        var balance = GetBalance();
        return balance.ToString("C");
    }
}

s3851781-a2-main/CustomerWebsite/Controllers/BillPayController.cs
using CustomerWebsite.Data;
using CustomerWebsite.Models;
using CustomerWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Controllers
{
    public class BillPayController : Controller
    {
        private readonly McbaContext _context;

        public BillPayController(McbaContext context) => _context = context;

        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

        public async Task<IActionResult> Index()
        {
            var accounts = await _context.Account.Where(x => x.CustomerID == CustomerID).ToListAsync();
            var billPays = await _context.BillPay.Where(x => accounts.Select(a => a.AccountNumber).Contains(x.AccountNumber)).ToListAsync();
            var failedBillPays = billPays.Where(x => x.Failed && x.Active).ToList();
            return View(new BillPayAndAlertsViewModel()
            {
                BillPays = billPays,
                HasAlerts = failedBillPays.Count > 0
            });
        }

        public async Task<IActionResult> Alerts()
        {
            var accounts = await _context.Account.Where(x => x.CustomerID == CustomerID).ToListAsync();
            var billPays = await _context.BillPay.Where(x => accounts.Select(a => a.AccountNumber).Contains(x.AccountNumber)).ToListAsync();
            var failedBillPays = billPays.Where(x => x.Failed && x.Active).ToList();
            
            return View(failedBillPays);
        }

        [HttpPost]
        public async Task<IActionResult> Alerts(int BillPayID)
        {
            var accounts = await _context.Account.Where(x => x.CustomerID == CustomerID).ToListAsync();
            var accountNumbers = accounts.Select(x => x.AccountNumber);
            var billPays = await _context.BillPay.Where(x => accountNumbers.Contains(x.AccountNumber) && x.BillPayID == BillPayID).ToListAsync();

            if (billPays.Count == 0)
            {
                return NotFound();
            }
            var billPay = billPays.First();
            billPay.Active = false;
            _context.Update(billPay);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Alerts));
        }

        public IActionResult CreateBillPay()
        {
            return View(new CreateBillPayViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreateBillPay(CreateBillPayViewModel payload)
        {
            if (!ModelState.IsValid)
            {
                return View(payload);
            }

            var account = _context.Account.FirstOrDefault(x => x.AccountNumber == payload.AccountNumber && x.CustomerID == CustomerID);
            
            if (account == null) {
                ModelState.AddModelError(nameof(payload.AccountNumber), "Account number can't be found");
                return View(payload);
            }

            var payee = _context.Payee.FirstOrDefault(x => x.PayeeID == payload.PayeeID);
            if (payee == null) {
                ModelState.AddModelError(nameof(payload.PayeeID), "Payee not found");
                return View(payload);
            }
            
            _context.BillPay.Add(
                new BillPay
                {
                    AccountNumber = account.AccountNumber,
                    PayeeID = payload.PayeeID,
                    Amount = payload.Amount > 0 ? payload.Amount : -payload.Amount,
                    ScheduleTimeUtc = payload.ScheduleTimeUtc,
                    Period = payload.Period,
                    Active = true,
                    Failed = false
                });

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Payees()
        {
            var payees = await _context.Payee.ToListAsync();
            return View(payees);
        }

        public IActionResult CreatePayee()
        {
            return View(new Payee());
        }
        
        [HttpPost]
        public async Task<IActionResult> CreatePayee(Payee payee)
        {
            if (!ModelState.IsValid)
            {
                return View(payee);
            }
              
            _context.Payee.Add(payee);
            await _context.SaveChangesAsync();

            return Redirect(nameof(Payees));
        }

        
        
    }
}

s3851781-a2-main/CustomerWebsite/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using CustomerWebsite.Data;
using CustomerWebsite.Models;
using SimpleHashing.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CustomerWebsite.Controllers;

[AllowAnonymous]
public class LoginController : Controller
{
    private static readonly ISimpleHash s_simpleHash = new SimpleHash();
    private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;
    
    private readonly McbaContext _context;

    public LoginController(McbaContext context) => _context = context;

    public IActionResult Login() => View();

    [HttpPost]
    public async Task<IActionResult> Login(string loginID, string password)
    {
        var login = await _context.Login.Include(x => x.Customer).FirstOrDefaultAsync(x => x.LoginID == loginID);

        if (login == null || string.IsNullOrEmpty(password) || !s_simpleHash.Verify(password, login.PasswordHash))
        {
            ModelState.AddModelError("Login Failed", "Login failed, please try again.");
            return View(new Login { LoginID = loginID });
        }

        if (login.Blocked)
        {
            ModelState.AddModelError("Login Failed", "Login blocked, please contact your bank.");
            return View(new Login { LoginID = loginID });
        }

        // Login customer.
        HttpContext.Session.SetInt32(nameof(Customer.CustomerID), login.CustomerID);
        HttpContext.Session.SetString(nameof(Customer.Name), login.Customer.Name);
        HttpContext.Session.SetString("ImageBase64", login.Customer.ImageBase64 ?? string.Empty);

        return RedirectToAction("Index", "Customer");
    }

    public IActionResult Logout()
    {
        // Logout customer.
        HttpContext.Session.Clear();

        return RedirectToAction("Index", "Home");
    }

    [Authorize]
    public IActionResult UpdatePassword()
    {
        var updatePasswordViewModel = new UpdatePasswordViewModel { };
        return View(updatePasswordViewModel);
    }

    [Authorize]
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> UpdatePassword(UpdatePasswordViewModel payload)
    {
        if (!ModelState.IsValid)
        {
            return View(payload);
        }

        var login = _context.Login.FirstOrDefault(x => x.CustomerID == CustomerID);
        var newPassword = payload.Password;
        var newPasswordHash = s_simpleHash.Compute(newPassword);
        login.PasswordHash = newPasswordHash;
        _context.Login.Update(login);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index", "Customer");
    }
}

s3851781-a2-main/CustomerWebsite/Controllers/TransactionController.cs
using CustomerWebsite.Data;
using CustomerWebsite.Models;
using CustomerWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CustomerWebsite.Controllers
{
    public class TransactionController : Controller
    {
        private readonly McbaContext _context;

        public TransactionController(McbaContext context) => _context = context;

        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

        public async Task<IActionResult> Deposit(int id)
        {
            var account = await _context.Account.FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null) { return NotFound(); }
            return View(account);
        }

        [HttpPost]
        public async Task<IActionResult> Deposit(int id, decimal amount, string? comment)
        {
            var account = await _context.Account.FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null)
            {
                ModelState.AddModelError(nameof(account), "The account you are trying to deposit to cannot be found.");
                return View(account);
            }

            var transactionService = new McbaTransactionService(_context);
            var error = await transactionService.Deposit(account, amount, comment);
            if (error != null)
            {
                ModelState.AddModelError(nameof(account), error);
                return View(account);
            }

            return RedirectToAction("Index", "Customer");
        }

        public async Task<IActionResult> Withdraw(int id)
        {
            var account = await _context.Account.FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null) { return NotFound(); }

            return View(account);
        }


        [HttpPost]
        public async Task<IActionResult> Withdraw(int id, decimal amount, string? comment)
        {
            var account = await _context.Account.Include(x => x.AccountTransactions).FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null)
            {
                ModelState.AddModelError(nameof(account), "The account you are trying to withdraw from cannot be found.");
                return View(account);
            }

            var transactionService = new McbaTransactionService(_context);
            var error = await transactionService.Withdraw(account, amount, comment);
            if (error != null)
            {
                ModelState.AddModelError(nameof(account), error);
                return View(account);
            }

            return RedirectToAction("Index", "Customer");
        }

        public async Task<IActionResult> Transfer(int id)
        {
            var account = await _context.Account.FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null) { return NotFound(); }

            return View(account);
        }

        [HttpPost]
        public async Task<IActionResult> Transfer(int id, int destinationAccountNumber, decimal amount, string? comment)
        {
            var account = await _context.Account.Include(x => x.AccountTransactions).FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            var destinationAccount = await _context.Account.FirstOrDefaultAsync(x => x.AccountNumber == destinationAccountNumber);

            if (account == null)
            {
                ModelState.AddModelError(nameof(account), "The account you are trying to transfer from cannot be found.");
                return View(account);
            }

            if (destinationAccount == null)
            {
                ModelState.AddModelError(nameof(account), "The account you are trying to transfer to cannot be found.");
                return View(account);
            }

            var transactionService = new McbaTransactionService(_context);
            var error = await transactionService.Transfer(account, destinationAccount, amount, comment);
            if (error != null)
            {
                ModelState.AddModelError(nameof(account), error);
                return View(account);
            }

            return RedirectToAction("Index", "Customer");
        }

        public async Task<IActionResult> MyStatements(int id)
        {
            var account = await _context.Account.Include(x => x.AccountTransactions).FirstOrDefaultAsync(x => x.AccountNumber == id && x.CustomerID == CustomerID);
            if (account == null) { return NotFound(); }

            var MyStatements = new MyStatementsViewModel
            {
                Transactions = account.AccountTransactions,
                AccountNumber = account.AccountNumber,
                Balance = account.GetBalance()
            };
            return View(MyStatements);
        }
    }
}

s3851781-a2-main/CustomerWebsite/Views/Shared/_AccountsTable.cshtml
@model IEnumerable<Account>
@using CustomerWebsite.Models.Types
@functions {
    public string GetAccountTypeString(string accountType) {
        switch (accountType) {
            case "C":
                return "Checking";
            case "S":
                return "Savings";
            default:
                return "Unknown";
        }
    }
}
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(x => x.First().AccountNumber)</th>
        <th>@Html.DisplayNameFor(x => x.First().AccountType)</th>
        <th>Balance</th>
        <th>Actions</th>
    </tr>
    @foreach(var account in Model) {
        <tr>
            <td>@Html.DisplayFor(x => account.AccountNumber)</td>
            <td>@GetAccountTypeString(account.AccountType)</td>
            <td>@account.GetBalanceString()</td>
            <td>
                <a class="btn btn-outline-primary btn-sm" asp-controller="Transaction" asp-action="Withdraw" asp-route-id="@account.AccountNumber">Withdraw</a>
                <a class="btn btn-outline-primary btn-sm" asp-controller="Transaction" asp-action="Deposit" asp-route-id="@account.AccountNumber">Deposit</a>
                <a class="btn btn-outline-primary btn-sm" asp-controller="Transaction" asp-action="Transfer" asp-route-id="@account.AccountNumber">Transfer</a>
                <a class="btn btn-outline-primary btn-sm" asp-controller="Transaction" asp-action="MyStatements" asp-route-id="@account.AccountNumber">My Statements</a>
            </td>
        </tr>
    }
</table>

s3851781-a2-main/CustomerWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MCBA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">MCBA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav d-flex align-items-center">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                            var hasProfilePicture = Context.Session.GetString("ImageBase64") != null && Context.Session.GetString("ImageBase64") != string.Empty;
                        }
                        @if(isLoggedIn) {
                            <li class="nav-item m-2">
                                <a asp-controller="Customer" asp-action="UpdateProfilePicture">
                                    <img src="@if(hasProfilePicture) {
                                            @Context.Session.GetString("ImageBase64")
                                         } else {
                                            @Url.Content("~/img/default_user.png")
                                         }" class="" style="width: 50px; height: 50px; object-fit: contain;" />
                                </a>
                            </li>
                            <li class="nav-item m-2">
                                <span class="nav-link text-dark">
                                    @Context.Session.GetString(nameof(Customer.Name))
                                </span>
                            </li>
                            <li class="nav-item m-2">
                                <a class="" asp-controller="Customer" asp-action="CustomerInformation">My Profile</a>
                            </li>
 
                            <li class="nav-item m-2">
                                <a class="" asp-controller="Customer" asp-action="Index">My Accounts</a>
                            </li>

                            <li class="nav-item m-2">
                                <a class="" asp-controller="BillPay" asp-action="Index">BillPay</a>
                            </li>
                            <li class="nav-item m-2">
                                <a class="btn btn-outline-primary" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        } else {
                            <li class="nav-item m-2">
                                <a class="btn btn-outline-primary" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>